name: Pylint

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      # Checkout the source code
      - name: Checkout Code
        uses: actions/checkout@v3
      # Setup correct Python version
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      # Install required libraries
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
            pip install pylint
            pip install umsgpack
            pip install cryptography
            pip install pylint-fail-under
      # Review code with Pylint and show suggestions
      - name: Review Code
        run: find . -name '*.py' -exec pylint {} \;
      # Fail build if Pylint score is below a given threshold
      - name: Evaluate Code
        run: find . -name '*.py' -exec pylint --fail-under=9.0 {} \;
